eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


microservice:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri: http://PAYMENT-SERVICE/payments/

  user-service:
    endpoints:
      fetchUserById:
        uri: http://USER-SERVICE/users/

logging:
  file:
    name: /Users/prate/OneDrive/Desktop/dev-logs/ecom.log
